[project]
name = 'green-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.DAO-governace]
path = 'contracts/DAO-governace.clar'
clarity_version = 3
epoch = 3.0

[contracts.funds-allocation]
path = 'contracts/funds-allocation.clar'
clarity_version = 3
epoch = 3.0

[contracts.impact-bond]
path = 'contracts/impact-bond.clar'
clarity_version = 3
epoch = 3.0

[contracts.project-registration]
path = 'contracts/project-registration.clar'
clarity_version = 3
epoch = 3.0

[contracts.project-vetting]
path = 'contracts/project-vetting.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
